nums = [-1, -3, -4, -6, -7, -9, 0, 2, 4, 5, 8, 9]
print("Original list of integers:")
print(nums)
print("\nEven numbers from the list:")
even_nums = list(filter(lambda x: x%2 == 0, nums))
print(even_nums)
print("\nOdd numbers from the list:")
odd_nums = list(filter(lambda x: x%2 != 0, nums))
print(odd_nums)
print("\nPositive numbers from the list:")
pos_nums = list(filter(lambda x: x > 0, nums))
print(pos_nums)
print("\nNegative numbers from the list:")
neg_nums = list(filter(lambda x: x < 0, nums))
print(neg_nums)