is_num = lambda q: q.replace('.','',1).isdigit()
print("\nPrint checking numbers:")
is_num1 = lambda r: is_num(r[1:]) if r[0]=='-' else is_num(r)
print(is_num1('-55.55'))
print(is_num1('-22.11'))
print(is_num('9.8'))
print(is_num('T2345'))
print(is_num('26587'))
print(is_num('78A9'))
print(is_num('0000'))
print(is_num('Apple'))